### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by khirakawa** [pdupavillon/nikeplus-client#4]
When I run `npm run test:client` with my username and password, I'm getting the following error:

```
{ NikeLoginError: Can't login
    at /Users/ken/work/nikeplus-client/src/nike.js:89:15
    at process._tickCallback (internal/process/next_tick.js:178:7)
  name: 'NikeLoginError',
  data:
   { code: 400,
     uri: 'https://unite.nike.com/login?appVersion=358&experienceVersion=308&uxid=com.nike.commerce.nikedotcom.web&locale=en_US&backendEnvironment=identity&browser=Google%20Inc.&os=undefined&mobile=false&native=false&visit=1&visitor=3db2a130-513a-11e8-bbcb-9b3ebb5c260d',
     body: '<HTML><HEAD>\n<TITLE>Access Denied</TITLE>\n</HEAD><BODY>\n<H1>Access Denied</H1>\n \nYou don\'t have permission to access "http&#58;&#47;&#47;unite&#46;nike&#46;com&#47;login&#63;" on this server.<P>\nReference&#32;&#35;18&#46;27010f17&#46;1525617122&#46;328da828\n</BODY>\n</HTML>\n' } }
```

Any idea why this might be happening?

**Comment by khirakawa** [comment]
I can't seem to login to nike's official my activity page due to https://awr.svs.nike.com/accesstoken throwing a 503 service unavailable.  I'm starting to think there's an issue on Nike's server side.

However, what I don't quite understand is how https://nike.bullrox.net is able to login and fetch my data.  From what I can tell, it's the only site that can successfully pull data from my nike+ run activity.

@pdupavillon If you can share details on how your site works, that would be tremendously helpful.  Apologies if you aren't the maintainer (I figured you are, given that the site is listed in this repo's description)
